### PR TITLE
Add Kotlin Bindings

### PR DESCRIPTION
**Pull request by f2prateek**

### CODE REVIEW

**Comment by chris-horner** [comment]
Hi @f2prateek. Were you still thinking of merging this in and just waiting for a review?

**Comment by f2prateek** [comment]
I was just playing around with what the implementation of Kotlin bindings could look like. I don't know if the RxSharedPreferencesCache is a good idea yet.

**Comment by kosiara** [comment]
Thanks for adding kotlin support.

**Comment by piotrek1543** [comment]
@f2prateek could you merge this branch. Some guys like me, uses Kotlin for daily work, so it would be good to have kotlin support

**Comment by chris-horner** [comment]
@piotrek1543 There's nothing stopping you from using rx-preferences with Kotlin right now. It works just fine. If you like the API that was being played around with here then you can easily define the extension functions in your own codebase. Kotlin is awesome 😄

**Pull request closed without merging**
