### PR TITLE
Convert Preference to an interface to allow easy mocking for unit tests

### LINKED ISSUE #32: Make Preference into an interface
Preference itself is a final class that can only be created through static methods in another class. You have created a unit test nightmare. You should change Preference into an interface and extract the implementation to another class. When using dependency injection the classes needing access to the Preference would inject the interface instead of a concrete class. That makes creating mock preferences for unit testing a breeze.

Without this, unit testing of classes that depend on a preference is much more difficult. It would require mocking SharedPreferences but having to capture the listener that is registered internally for preference changes.

### PR DESCRIPTION
**Pull request by dalewking**
resolves #32

### CODE REVIEW

**Comment by dalewking** [comment]
You might want to rename the PreferenceImpl class to suit your taste and you could actually make it non-public.

In reality the Adapter interface makes a lot more sense in RxSharedPreferences class rather than the Preference interface, but that would be a breaking change to users of the library so I left it in Preference interface.

**Comment by JakeWharton** [comment]
This is already a binary-incompatible change as is so it is breaking. And
of course the implementation shouldn't be public.

**Comment by dalewking** [comment]
Yeah, I missed that Android Studio kept it public before pushing it.

I disagree that this is a binary incompatible change. Consumers of this API accessed preferences through Preference and continue to do so. The external API hasn't changed.

**Comment by JakeWharton** [comment]
Previously it was an invokevirtual call and now it's invokeinterface. That
is binary incompatibility.

**Comment by dalewking** [comment]
Unless there is some library that was created in the last 3 weeks that depends on this library it is hard to imagine how anyone will really be affected by that binary incompatibility. Any source code that depends on this library is not affected by the change at all. However the inability to easily unit test a class that uses preferences is going to affect a lot of users.

**Comment by JakeWharton** [comment]
Semver is not subjective. And your claims are not backed by fact, merely
one person's need.

**Comment by JakeWharton** [comment]
I'm not against this, FWIW, just want it to be driven by the right reasons.

**Comment by dalewking** [comment]
The point is that this library has only been around a few weeks, so binary incompatibility is probably not a huge issue compared to difficulty in unit testing classes that depend on it. It is possible to do it and here is the code I added to a base class for the unit tests to be able to drive unit tests. (Note this code is using RetroLambda and Java 8 Stream support):

	@Mock protected SharedPreferences mockSharedPreferences;

	@Mock protected SharedPreferences.Editor mockPreferenceEditor;

	protected RxSharedPreferences rxSharedPreferences;

	protected final List<SharedPreferences.OnSharedPreferenceChangeListener> preferenceListeners
			= new ArrayList<>();

	@Before
	public void preferencesSetup()
	{
		rxSharedPreferences = RxSharedPreferences.create(mockSharedPreferences);

		doAnswer(invocation -> {
			preferenceListeners.add((SharedPreferences.OnSharedPreferenceChangeListener)
					invocation.getArguments()[0]);
			return null;
		}).when(mockSharedPreferences).registerOnSharedPreferenceChangeListener(any());

		doAnswer(invocation -> {
			preferenceListeners.remove(invocation.getArguments()[0]);
			return null;
		}).when(mockSharedPreferences).unregisterOnSharedPreferenceChangeListener(any());

		when(mockSharedPreferences.edit()).thenReturn(mockPreferenceEditor);
	}

	protected void notifyPreferenceChange(String key)
	{
		Stream.of(preferenceListeners)
				.forEach(listener -> listener.onSharedPreferenceChanged(mockSharedPreferences, key));
	}

The ability to just mock Preference as an interface would be a lot easier.

**Comment by JakeWharton** [comment]
I know your arguments, and you continue to ignore what I say. Even if 1.0
was released 5m ago this would be a binary-incompatible change requiring a
major version bump.

**Comment by wuman** [comment]
If making a major version change is such a big concern, how about just keep the implementation and remove the `final` from the `Preference` class?  This will not require a major version change while allowing callers to easily mock a Preference.

**Comment by Endran** [comment]
I agree with Wuman, this issue has been open for almost 4 months. I understand why people like final classes; "Design and document for inheritance or else prohibit it". The theory is nice, but in practise we need open classes for testability. Not being able to properly test something is in my opinion worse that having a non-final class, without an interface.

**Comment by zhengxiaopeng** [comment]
:-<  Unit test nightmare. I also agree with @wuman .

**Comment by f2prateek** [comment]
@wuman @zhengxiaopeng Just to be clear, the Preference class can be easily tested without this change in on-device unit tests and instrumentation tests. JVM unit tests are also possible with Robolectric as done in this library or with mocked SharedPreferences. Nothing is blocking you from implementing one of those approaches.

**Comment by dalewking** [comment]
> Just to be clear, the Preference class can be easily tested without this change in unit tests
> and instrumentation tests on devices.

on device unit tests is pretty much a contradiction in terms

> JVM unit tests are also possible with Robolectric as done in this library or with mocked
> SharedPreferences. Nothing is blocking you from implementing one of those approaches.

I beg to differ. I tried implementing it with Robolectric and it was pretty much a disaster. It felt like I was writing unit tests for RxPreferences not my code. I ended up creating my own interface and creating a wrapper to translate to your class.

Just to be clear converting Preference to an interface would make this trivial in all cases. The only argument I have heard against it is that the new version should be 2.x instead of 1.x. And that is a problem, why?

**Comment by f2prateek** [comment]
How were you using Robolectric? Seems to me like you weren't using it correctly if it was a complete disaster.

**Comment by f2prateek** [comment]
Here some simple examples:

```java
SharedPreferences preferences = PreferenceManager.getDefaultSharedPreferences(context);
RxSharedPreferences rxPreferences = RxSharedPreferences.create(preferences);
Preference<Boolean> foo = rxPreferences.getBoolean("foo", false);
```

```java
void testFooIsEnabled() {
  foo.set(false);
  enableFoo();
  assertThat(foo.get()).is(true);
}
```

```java
void testReturns4WhenFooIsTrue() {
  foo.set(true);
  int result = someActionBasedOnFoo();
  assertThat(result).is(4);
}
```

```java
void testReturns5WhenFooIsFalse() {
  foo.set(false);
  int result = someActionBasedOnFoo();
  assertThat(result).is(5);
}
```

**Comment by JakeWharton** [comment]
> on device unit tests is pretty much a contradiction in terms

Android has shipped with JUnit since API 1 and has supported both unit tests and instrumentation tests (which are just specialized unit tests with access to `Instrumentation`). Try again.

**Comment by wuman** [comment]
I don't have a problem writing unit tests for rx-preferences.

My biggest pain point with the API is that they are too restrictive:  classes being `final` or unexposed.  In one of my projects I wanted to extend rx-preferences to support encryption of both the key and the value of a preference.  This turned out to be more cumbersome than I first anticipated.  I ended up needing to rewrite the `RxSharedPreferences` class and each of the unexposed adapters.

**Comment by troyjperales** [comment]
@wuman Since SharedPreferences is an interface, we were able to support encryption fairly easily at that layer without having to modify RxSharedPreferences e.g. EncryptedSharedPreferences.

**Comment by wuman** [comment]
@troyjperales Thanks for the suggestion.  I hadn't thought of that.  It is indeed a more elegant approach.

**Comment by floating-cat** [comment]
I agree with wuman too.
Though Robolectric can solve this problem, but I think this is still inconvenient.
If you use adapter, you need write at least four unimportant line code and related adapter for this `Preference`. Though helper method or something like robot pattern jake talked could solve this problem.
And IMHO it is also anti-pattern and more inconvenient to mock SharedPreferences which  f2prateek mentioned in order to use this mock object to create `Preference`.

I am not lazy to write this three or four line code for test, and write this words cost me much time to this three or four line code.
I hope not anyone like me want to mock `Preference` and found this is final not a interface or abstract class and because I use Mockito so I can't mock this and try to workaround it.

**Pull request closed without merging**
