### PR TITLE
Jsr305, MinSdk 14

### PR DESCRIPTION
**Pull request by PaulWoitaschek**
* Updated dependencies and removed unused imports. 
* Use a consistent code formatting.
* Replaced the NonNull annotations with jsr305.
* MinSdk 14 en pair with support libraries.

### CODE REVIEW

**Comment by f2prateek** [comment]
This is just changing the code style, not really making it consistent with what was in already in place.

Please break out the other changes into their own PRs as well.

**Comment by PaulWoitaschek** [comment]
Do you aggree with all changes?
* Min-Sdk14
* Dependency update
* Jsr310?

Can you define the code style somehwere? For example sometimes annotations are wrapping, sometimes they are on the same line

**Comment by JakeWharton** [comment]
I don't see a motivation to switch to JSR 305.

**Comment by PaulWoitaschek** [comment]
Well completely everything here is not nullable, so it reduces a lot of boilerplate code.

**Comment by JakeWharton** [comment]
But it's vastly less supported than support-annotations in the tools we use
so you'd be regressing the nullability explicitness.

**Pull request closed without merging**
