### PR TITLE
Make enum adapter null-safe.

### PR DESCRIPTION
**Pull request by JakeWharton**
These aren't individually tested, unfortunately.

### CODE REVIEW

**Comment by f2prateek** [comment]
LGTM. Is there a valid use case for accepting `null` values in `Preference#set`? Clients should be able to use `Preference#delete` instead for most caes.

If there is, we'll need to update most of the other adapters as well, otherwise the code below will throw too.

```java
RxSharedPreferences rxPreferences = RxSharedPreferences.create(preferences);
Preference<Float> preference = rxPreferences.getFloat("foo");
preference.set(null);
```

**Comment by JakeWharton** [comment]
The reason that I think allowing `null` makes sense is so that you can "clear" a preference when using the `Action0` form. I looked through all of the other adapters and they are null-friendly. This was the only one that would NPE.

**Comment by f2prateek** [comment]
Auto-unwrapping `null` values throws a NPE in the other adapters.

All of these test cases below will throw a NPE.

```java
  @Test public void setBooleanNull() {
    RxSharedPreferences.create(preferences).getBoolean("a").set(null);
  }

  @Test public void setIntegerNull() {
    RxSharedPreferences.create(preferences).getInteger("b").set(null);
  }

  @Test public void setFloatNull() {
    RxSharedPreferences.create(preferences).getFloat("c").set(null);
  }

  @Test public void setLongNull() {
    RxSharedPreferences.create(preferences).getLong("d").set(null);
  }
```

**Comment by JakeWharton** [comment]
Oh because the editor methods are primitives? I never even knew. Maybe we
just special case null in the action to perform a delete.

**Pull request closed without merging**
